baseURL = "https://cvqa-benchmark.org/"
languageCode = "en-us"
title = "CVQA: A Culturally-diverse Multilingual Visual Question Answering Benchmark"
theme = "my_theme"

[params]
  description = "A Culturally-diverse Multilingual Visual Question Answering Benchmark"
  ogTitle = "CVQA: A Culturally-diverse Multilingual Visual Question Answering Benchmark"
  ogDescription = "This is a culturally-diverse Multilingual Visual Question Answering Benchmark"
  twitterTitle = "CVQA: A Culturally-diverse Multilingual Visual Question Answering Benchmark"
  twitterDescription = "This is a culturally-diverse Multilingual Visual Question Answering Benchmark"
  keywords = "multimodal, vlm, nlp, computer vision, benchmark, dataset, vqa"

[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    isHTML = true
    noUgly = true

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["html"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false
    noClasses = false

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  taxonomyTerm = ["HTML"]
  page = ["HTML"]
  alias = ["HTML"]
  sitemap = ["XML"]
